services:
  - type: web
    name: autoclipper
    env: python
    region: oregon
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --workers 2 --threads 4 --timeout 300
    envVars:
      - key: R2_ENDPOINT_URL
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
